### ISSUE TITLE
No packets captured

### ISSUE THREAD

**Issue by moha-abdi** [fkie-cad/friTap#10]
Hello, I have already seen an issue like this, but none of the soultions worked for me. I am on IOS 16.0, and I am also using Windows. I have tested it with more than 10 applications, and all the packets were empty. I will leave some screenshots below.

![image](https://github.com/fkie-cad/friTap/assets/83307623/060bda86-806c-4975-a4a7-ab5a68b054ad)

All the packets as in the below screenshot were 24 bytes or empty. I dont knw if the issue is specific to me or not, bt I will try and find a solution.

![image](https://github.com/fkie-cad/friTap/assets/83307623/2cbf7928-c473-44ec-8b7a-4e5d6a557c10)

**Comment by moha-abdi** [comment]
I think friTap doesnt fully suppot IOS 15 and 16, because in `OpenSSL_BoringSSL_iOS ` class, the offset is outdated for IOS 15 and for IOS 16 aswell. For my IOS 16 after I modified the offset to `0x300` I can now see TLS keys, but I think it still needs some updates.

**Comment by monkeywave** [comment]
Hi,

yes you are right the support for iOS is currently really "bad" and only consider iOS <= 14. Furthermore only the TLS key extraction is supported for this iOS version. Do you know if the offset 0x300 will also work for iOS 15? 

Currently we have at first fix the issues with the new Android version. Than we want to focus finally on iOS to improve there the capability of friTap :-)

**Comment by monkeywave** [comment]
This issue is now solved with some newer iOS versions (till iOS 17) but only the capability to log the TLS keys. Regarding the feature to write only the plaintext into a PCAP further research is still needed.
