### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by blv-chris-mcmahon** [fkie-cad/friTap#13]
Hello. Thanks for this great project. I'm interesting in helping to add support for Flutter based apps. Is there any info/insights you can provide me to help get started? Thanks!

**Comment by monkeywave** [comment]
Hello, thx you for your request, as we can always use support to extend the capabilities of friTap to other libraries/technologies :-)

So I think this might help in the beginning:
https://github.com/fkie-cad/friTap/blob/main/CONTRIBUTION.md

For further question don't hesitate to write me an email (you can find it down in the README.md)

**Comment by monkeywave** [comment]
We have now for Android and iOS Flutter support so friTap is able to extract the key material.
