### ISSUE TITLE
Issues with Nox emulator

### ISSUE THREAD

**Issue by thecoder8324** [fkie-cad/friTap#20]
I have an instance of nox rooted with usb debugging enabled and connected to a frida-server. However, when I attempt to run the command fritap -m -k keys.log -v -s <Package Name>, I get this error:
[-] Unknown error: device not found
I've also tried running it with the command fritap -H 127.0.0.1:62027 -k keys.log -v -s <Package Name> as this appears to be the ip and port of my connected device, but I get:
[-] Unknown error: connection closed

Any advice on how to configure fritap to work with nox (or any emulator) apps would be appreciated. Thanks!

**Comment by monkeywave** [comment]
Hi,

at first thx for reporting this issue. Did you already tried that you are able to use frida on this devices? 
If frida is not working, friTap won't work either.

**Comment by thecoder8324** [comment]
Hello,

Yes, frida appears to be working. I'm able to run objection and frida scripts just fine, for instance. I'm also using windows if that makes a difference.
Does the -m flag generally work with emulators such as Nox?

**Comment by monkeywave** [comment]
Hi,

regarding your question: The `-m`-parameter should normally work with Emulators. Test with the default Android Emulator (AVD) and Corellium has been successful. Did you tried the invocation without the `-s`-parameter? 

We never tried it with the Nox emulator.

**Comment by thecoder8324** [comment]
I tried running the command with Android studio's AVD and without the -s parameter. In both cases I get the same error messages of either 'device not found' or 'connection closed'. Interestingly, android studio was able to detect my nox emulator, but FriTap could not. The only thing I can think of is maybe it's firewall/permissions related.

Also just to be sure, for the -H flag should we supply the IP and port listed under adb connected devices? For example, if I run the command 'adb devices' I get a list of devices attached containing one device listed as '127.0.0.1:62027' and have used this for the -H parameter. 
Thanks for the help.
