### ISSUE TITLE
Allow startup script before logging

### ISSUE THREAD

**Issue by NgoHuy** [fkie-cad/friTap#25]
Hi team,
Thank you for your greate repo. 

I think we need to add options to load custom scripts before logging TLS. Because some applications have protection, it terminated before running. Loading custom script to bypass it, it's nice feature.

**Comment by monkeywave** [comment]
Hi,

thx for this request. Actually we are currently working on that and will soon release something.


All the best

Daniel

**Comment by monkeywave** [comment]
Thank you for your patience! We're excited to announce that the latest release, friTap 1.2.4.0, introduces a new feature allowing you to execute custom Frida scripts using the `-c` parameter. This feature enables running your scripts before friTap applies its own hooks, providing greater flexibility and customization.

For more details, check out the [USAGE.md](./USAGE.md#Using-friTap-with-a-custom-Frida-scripts) section.

All the best

Daniel
