### ISSUE TITLE
Python 3.12 not supported because of 'distutils' removal

### ISSUE THREAD

**Issue by techware01** [fkie-cad/friTap#29]
Currently friTap is not working when using Python 3.12. 

When running it I get the following error `ModuleNotFoundError: No module named 'distutils'`

This seems to be due to removal of the former, but now deprecated standard module `distutils`in python 3.12 (See [relase-notes](https://docs.python.org/3/whatsnew/3.12.html)). 

For now a workaround that worked for me, is to manually install `setuptools`, which also provides 'distutils'. Following the suggestion on [Stackoverflow](https://stackoverflow.com/questions/77247893/modulenotfounderror-no-module-named-distutils-in-python-3-12):

```
$ pip3 install setuptools
```

Any plans on porting friTap to Python 3.12?

**Comment by monkeywave** [comment]
Thx for reporting this issue - will look into this :-)

**Comment by monkeywave** [comment]
Hi, 

this should at least not be an issue in the latest version of friTap (version 1.1.1.0). 

As you can see, no `setuptools` is installed but friTap was installed.

```
$ pip3 freeze        
AndroidFridaManager==1.7.9
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
colorlog==6.8.2
frida==16.0.11
frida-tools==12.1.1
friTap==1.1.1.0
hexdump==3.3
idna==3.7
importlib_resources==6.4.0
prompt-toolkit==3.0.38
Pygments==2.14.0
requests==2.32.3
scapy==2.5.0
typing_extensions==4.5.0
urllib3==2.2.2
watchdog==4.0.1
wcwidth==0.2.6
```

If you still encounter this problem just reopen this issue and provide information about which friTap version you tried on which operating system.
