### ISSUE TITLE
Unknown error: 'SSL_Logger' object has no attribute 'debug_mode'

### ISSUE THREAD

**Issue by freako89** [fkie-cad/friTap#31]
Hi friTap team, when I ran `fritap` on Ubuntu, I got this issue.

```
Start logging
Press Ctrl+C to stop logging
[***] loading frida script: _ssl_log.js

[-] Unknown error: 'SSL_Logger' object has no attribute 'debug_mode'


Thx for using friTap
Have a great day
```

Please assist in resolving this issue, I appreciate your attention.

**Comment by monkeywave** [comment]
Hi,

thx for reporting this issue. This should be resolved in the latest release. If you still encounter this problem, feel free to reopen this issue.
