### ISSUE TITLE
 capturing firefox error on windows .

### ISSUE THREAD

**Issue by cts2021** [fkie-cad/friTap#33]
fritap --pcap mycapture.pcap  firefox.exe
Start logging
Press Ctrl+C to stop logging
[*] capturing only plaintext data
[-] ProcessNotFoundError: ambiguous name; it matches: firefox.exe (pid: 6288), firefox.exe (pid: 3444), firefox.exe (pid: 3132), firefox.exe (pid: 4732), firefox.exe (pid: 17496), firefox.exe (pid: 6232), firefox.exe (pid: 16988), f
irefox.exe (pid: 1268), firefox.exe (pid: 12900), firefox.exe (pid: 19668), firefox.exe (pid: 2396), **firefox.exe (pid: 3636)**

fritap --pcap mycapture.pcap  3636       
Start logging
Press Ctrl+C to stop logging
[*] capturing only plaintext data

**[-] Unknown error: unexpectedly failed with error code: 0x00000057**

Thx for using friTap
Have a great day

**Comment by cts2021** [comment]
firefox   version 132.0.1
windows 10 x64

**Comment by monkeywave** [comment]
Hi,

Thanks for using friTap and for reporting this issue. The Windows hooks in friTap tend to work best when used solely for extracting TLS key material. You might have better success by running friTap with the following command:

```shell
friTap -k firefox_keys.log 3636
```

However, the error message does look unusual. Have you tried hooking the same Firefox process directly with Frida?
```shell
frida -p 3636
```

If Frida does not work on its own, then friTap won’t work either, as it’s built on top of Frida.

If Frida is working but friTap still encounters this crash, could you try running friTap in debug-output mode as described in the [troubleshooting section of the documentation](https://github.com/fkie-cad/friTap/blob/main/README.md#seeking-further-assistance)?
```shell
fritap -do -v com.example.app
```

All the best

Daniel

**Comment by monkeywave** [comment]
It seems that this error is related to the used Frida version (cf. [1]).
Which Frida version are you using?

It might help to downgrade to Frida version 16.4.10.

All the best

Daniel


[1] https://github.com/frida/frida/issues/2964
