### ISSUE TITLE
Traffic is not being captured

### ISSUE THREAD

**Issue by dev7machine** [fkie-cad/friTap#6]
Hi, I am trying to capture traffic and logs showing that tool is working fine but I am getting empty pcap file (24 bit size). I have tried 4-5 different mobile apps and none of them worked. 

Tried latest friTap via pypi as well as cloned repo. 

Tried two different frida-tool/server versions. Frida is working fine

![Screenshot from 2023-01-21 04-59-45](https://user-images.githubusercontent.com/58460817/213827268-2b1bf846-dbed-4426-84fd-e5e5e999fada.png)

pcap files
![Screenshot from 2023-01-21 05-04-02](https://user-images.githubusercontent.com/58460817/213827299-95464dc2-e009-4cc3-817e-e1d1bd95a6c9.png)

**Comment by monkeywave** [comment]
Hi, 

thx for reporting this issue. Is it possible to share the target APK in order to reproduce the error in our dev environment?

**Comment by dev7machine** [comment]
I have tried 4-5 different apps and none of them worked. Here is the one `com.telenor.pakistan.mytelenor`
PlayStore [link](https://play.google.com/store/apps/details?id=com.telenor.pakistan.mytelenor&hl=en&gl=US)

2nd One 
[io.maqsad](https://play.google.com/store/apps/details?id=io.maqsad)

**Comment by Aniketh01** [comment]
@dev7machine which android version are you testing these apps on?

**Comment by mywalkb** [comment]
I have the same issue.
I have Android 12 (MIUI 13.5) (arm64)
Frida version 16.0.19 latest.
My client is a debian 11.
I'm testing telegram, I have the same issue on other apps.

```
./friTap.py -m -s --pcap test.pcap org.telegram.messenger
Start logging
spawning org.telegram.messenger
Press Ctrl+C to stop logging.
/home/user/friTap/friTap/_ssl_log.js
[*] Running Script on Android
[*] libssl.so found & will be hooked on Android!
[*] Android dynamic loader hooked.
Init watcher
INITIALIZED
/home/user/friTap
[*] Logging TLS plaintext as pcap to test.pcap
^C

Thx for using friTap
Have a nice day
```
```
ls -l test.pcap 
-rw-r--r-- 1 user user 24 apr 29 08:39 test.pcap
```

pcap file is only 24 byte, is empty no packets

**Comment by mywalkb** [comment]
I tested on Android 9 x86 and works, I tested on Android 11 arm64 LineageOS 19.1 and doesn't work.
Always the same version of frida and the same client.

**Comment by konsumer** [comment]
I tried with Google Play Store on Android 11 (arm64 emulator) with similar results. tcpdump captures packets fine, and using this, for example, captures (some) keys:

```
frida -U --codeshare vadim-a-yegorov/universalkeylogger -f com.android.vending
```
