### ISSUE TITLE
Conscrypt hooking on Android 13 generates segfault

### ISSUE THREAD

**Issue by LVerneyPEReN** [fkie-cad/friTap#8]
Hi,

I tried using friTap and conscrypt hooking on an Android 13 device running latest Lineage with MicroG. When spawning the app through friTap, I get a segfault / "Process terminated" error. I do not get the same error when attaching to a running app.

I managed to trace it back to [this line](https://github.com/fkie-cad/friTap/blob/main/agent/android/conscrypt.ts#L17-L18) and commenting it does solve the issue.

This is reproducible with both the microG implementation and the GMS one.

I can provide further informations and steps to reproduce privately if this might be useful for debugging.

Best

**Comment by monkeywave** [comment]
Hi,

thx for reporting this issue. We'll have a look into this.

**Comment by monkeywave** [comment]
Hi,

I have several questions regarding your issue:

- So if I understand you right, when you commenting the mentioned lines it works as expected or does it introduce other problems?
- Can you provide more information and steps to reproduce it? If you don't want to expose them here publicly you can send me an email (see https://github.com/fkie-cad/friTap/blob/main/README.md )

Thx :-)

**Comment by monkeywave** [comment]
Should be fixed in latest release. If not just reopen this issue :-)
